"""Data models for business listings."""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class Listing:
    """Represents a single e-commerce business listing.

    Fields are divided into:
      - Identity: URL, source marketplace, name
      - Financials: price, revenue, profit (from API)
      - Metadata: platform, age, location (from API)
      - Listing text: title + description (for AI summarization)
      - Qualification: pass/fail result from filters
      - AI analysis: summary generated by Gemini from listing text
    """

    # Identity
    url: str
    source: str  # "flippa", "empire_flippers", etc.
    business_name: str
    niche: str = ""

    # Financials (from API)
    asking_price: float = 0.0
    monthly_revenue: float = 0.0
    monthly_net_profit: float = 0.0
    annual_revenue: float = 0.0
    annual_net_profit: float = 0.0
    revenue_trend_yoy: Optional[float] = None  # percentage, e.g. 0.15 = +15%

    # Derived financials
    @property
    def profit_multiple(self) -> float:
        if self.annual_net_profit and self.annual_net_profit > 0:
            return self.asking_price / self.annual_net_profit
        return float("inf")

    @property
    def net_margin_pct(self) -> float:
        if self.monthly_revenue and self.monthly_revenue > 0:
            return (self.monthly_net_profit / self.monthly_revenue) * 100
        return 0.0

    # Platform / age / location (from API)
    platform: str = ""
    business_age_months: int = 0
    seller_location: str = ""

    # Listing text (for AI summarization)
    listing_title: str = ""
    description: str = ""

    # Qualification result (filled by qualifier)
    qualified: bool = False
    disqualify_reason: str = ""

    # Deal score (0-100) — ranks qualified listings for AI prioritization
    deal_score: int = 0

    # AI analysis (filled by Gemini summarization)
    ai_summary: str = ""
    ai_verdict: str = ""  # "STRONG BUY" / "INVESTIGATE" / "PASS"
    ai_strengths: str = ""
    ai_risks: str = ""
    ai_growth_moves: str = ""

    # Metadata
    date_found: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d"))

    def to_sheet_row(self) -> list:
        """Convert to a row for Google Sheets output."""
        return [
            self.url,
            self.source,
            self.business_name,
            self.niche,
            f"${self.asking_price:,.0f}",
            f"${self.monthly_revenue:,.0f}",
            f"${self.monthly_net_profit:,.0f}",
            f"{self.profit_multiple:.1f}x" if self.profit_multiple != float("inf") else "N/A",
            f"{self.net_margin_pct:.1f}%",
            self.deal_score,
            self.platform,
            f"{self.business_age_months} mo",
            self.seller_location,
            self.ai_summary,
            self.ai_verdict,
            self.ai_strengths,
            self.ai_risks,
            self.ai_growth_moves,
            self.date_found,
        ]
